export commit=1f5ff08d5d2232c3789340f3e0803a7a00bc3684
git checkout $commit~1 mwb/media/accrington.png
git checkout $commit~1 mwb/media/accringtonstanley.png
git checkout $commit~1 mwb/media/afcwimbledon.png
git checkout $commit~1 mwb/media/aldershottown.png
git checkout $commit~1 mwb/media/arsenal.png
git checkout $commit~1 mwb/media/astonvilla.png
git checkout $commit~1 mwb/media/aw.png
git checkout $commit~1 mwb/media/awimbledon.png
git checkout $commit~1 mwb/media/b2.jpg
git checkout $commit~1 mwb/media/b3.jpg
git checkout $commit~1 mwb/media/barnet.png
git checkout $commit~1 mwb/media/barnsley.png
git checkout $commit~1 mwb/media/bet-at-home-button.png
git checkout $commit~1 mwb/media/bet365.jpg
git checkout $commit~1 mwb/media/bet365.png
git checkout $commit~1 mwb/media/betfair.jpg
git checkout $commit~1 mwb/media/betfair.png
git checkout $commit~1 mwb/media/betfred.png
git checkout $commit~1 mwb/media/betvictor.png
git checkout $commit~1 mwb/media/bg.png
git checkout $commit~1 mwb/media/birmingham.png
git checkout $commit~1 mwb/media/blackburn.png
git checkout $commit~1 mwb/media/blackburnrovers.png
git checkout $commit~1 mwb/media/blackpool.png
git checkout $commit~1 mwb/media/boffin.jpg
git checkout $commit~1 mwb/media/bolton.png
git checkout $commit~1 mwb/media/bournemouth.png
git checkout $commit~1 mwb/media/bradford.png
git checkout $commit~1 mwb/media/brentford.png
git checkout $commit~1 mwb/media/brighton.png
git checkout $commit~1 mwb/media/bristolcity.png
git checkout $commit~1 mwb/media/bristolrovers.png
git checkout $commit~1 mwb/media/bristolrvs.png
git checkout $commit~1 mwb/media/burnley.png
git checkout $commit~1 mwb/media/burton.png
git checkout $commit~1 mwb/media/bury.png
git checkout $commit~1 mwb/media/cardifity.png
git checkout $commit~1 mwb/media/carlisle.png
git checkout $commit~1 mwb/media/charlton.png
git checkout $commit~1 mwb/media/chelsea.png
git checkout $commit~1 mwb/media/cheltenham.png
git checkout $commit~1 mwb/media/chesterfield.png
git checkout $commit~1 mwb/media/colchester.png
git checkout $commit~1 mwb/media/coral.png
git checkout $commit~1 mwb/media/coventrycity.png
git checkout $commit~1 mwb/media/cpalace.png
git checkout $commit~1 mwb/media/crawleytown.png
git checkout $commit~1 mwb/media/crewe.png
git checkout $commit~1 mwb/media/crystalpalace.png
git checkout $commit~1 mwb/media/dagandred.png
git checkout $commit~1 mwb/media/dagred.png
git checkout $commit~1 mwb/media/derby.png
git checkout $commit~1 mwb/media/doncaster.png
git checkout $commit~1 mwb/media/everton.png
git checkout $commit~1 mwb/media/exeter.png
git checkout $commit~1 mwb/media/fleetwoodtown.png
git checkout $commit~1 mwb/media/focus.png
git checkout $commit~1 mwb/media/fsq0.png
git checkout $commit~1 mwb/media/fsq07081.png
git checkout $commit~1 mwb/media/fsq08081.png
git checkout $commit~1 mwb/media/fsq08083.png
git checkout $commit~1 mwb/media/fsq9.png
git checkout $commit~1 mwb/media/fsqfg1.png
git checkout $commit~1 mwb/media/fsqgame.png
git checkout $commit~1 mwb/media/fsqgauche.png
git checkout $commit~1 mwb/media/fsqpopf.png
git checkout $commit~1 mwb/media/fsqyell.png
git checkout $commit~1 mwb/media/fulham.png
git checkout $commit~1 mwb/media/gillingham.png
git checkout $commit~1 mwb/media/hartlepool.png
git checkout $commit~1 mwb/media/hereford.png
git checkout $commit~1 mwb/media/homeBtnImg.png
git checkout $commit~1 mwb/media/huddersfield.png
git checkout $commit~1 mwb/media/hull.png
git checkout $commit~1 mwb/media/hullcity.png
git checkout $commit~1 mwb/media/ic_launcher.png
git checkout $commit~1 mwb/media/icon-close-open.png
git checkout $commit~1 mwb/media/ipswich.png
git checkout $commit~1 mwb/media/ladbrokes.png
git checkout $commit~1 mwb/media/leeds.png
git checkout $commit~1 mwb/media/leedsunited.png
git checkout $commit~1 mwb/media/leicester.png
git checkout $commit~1 mwb/media/leicestercity.png
git checkout $commit~1 mwb/media/level1.png
git checkout $commit~1 mwb/media/levellock.png
git checkout $commit~1 mwb/media/leytonorient.png
git checkout $commit~1 mwb/media/liverpool.png
git checkout $commit~1 mwb/media/lock.png
git checkout $commit~1 mwb/media/luton.png
git checkout $commit~1 mwb/media/macclesfield.png
git checkout $commit~1 mwb/media/manchestercity.png
git checkout $commit~1 mwb/media/manchesterunited.png
git checkout $commit~1 mwb/media/manchesterutd.png
git checkout $commit~1 mwb/media/mancity.png
git checkout $commit~1 mwb/media/mansfield.png
git checkout $commit~1 mwb/media/manutd.png
git checkout $commit~1 mwb/media/mb.jpg
git checkout $commit~1 mwb/media/mb1.jpg
git checkout $commit~1 mwb/media/mb1.png
git checkout $commit~1 mwb/media/mb2.jpg
git checkout $commit~1 mwb/media/mb2.png
git checkout $commit~1 mwb/media/mb2a.jpg
git checkout $commit~1 mwb/media/mb2b.jpg
git checkout $commit~1 mwb/media/mb3.jpg
git checkout $commit~1 mwb/media/mb3.png
git checkout $commit~1 mwb/media/mb3a.jpg
git checkout $commit~1 mwb/media/mb3b.jpg
git checkout $commit~1 mwb/media/mb4.jpg
git checkout $commit~1 mwb/media/mb4.png
git checkout $commit~1 mwb/media/mb4a.jpg
git checkout $commit~1 mwb/media/mb4b.jpg
git checkout $commit~1 mwb/media/mb5.jpg
git checkout $commit~1 mwb/media/mb5.png
git checkout $commit~1 mwb/media/mb6.jpg
git checkout $commit~1 mwb/media/mb6.png
git checkout $commit~1 mwb/media/mb6a.jpg
git checkout $commit~1 mwb/media/mb7.jpg
git checkout $commit~1 mwb/media/mb8.jpg
git checkout $commit~1 mwb/media/mb9.jpg
git checkout $commit~1 mwb/media/middlesbrough.png
git checkout $commit~1 mwb/media/millwall.png
git checkout $commit~1 mwb/media/miltonkeynesdons.png
git checkout $commit~1 mwb/media/mkdons.png
git checkout $commit~1 mwb/media/morecambe.png
git checkout $commit~1 mwb/media/mwb1.png
git checkout $commit~1 mwb/media/mwb2.png
git checkout $commit~1 mwb/media/mwb3.png
git checkout $commit~1 mwb/media/mwb4.png
git checkout $commit~1 mwb/media/mwb5.png
git checkout $commit~1 mwb/media/mwb6.png
git checkout $commit~1 mwb/media/mwbbeach.jpg
git checkout $commit~1 mwb/media/mwbbeach.png
git checkout $commit~1 mwb/media/mwbbeach2.jpg
git checkout $commit~1 mwb/media/mwbbeach4.png
git checkout $commit~1 mwb/media/mwbbeach5.png
git checkout $commit~1 mwb/media/mwbtop.jpg
git checkout $commit~1 mwb/media/mwbtop2.jpg
git checkout $commit~1 mwb/media/newcastle.png
git checkout $commit~1 mwb/media/newcastleunited.png
git checkout $commit~1 mwb/media/newcastleutd.png
git checkout $commit~1 mwb/media/newportcounty.png
git checkout $commit~1 mwb/media/northampton.png
git checkout $commit~1 mwb/media/norwich.png
git checkout $commit~1 mwb/media/nottinghamforest.png
git checkout $commit~1 mwb/media/nottmforest.png
git checkout $commit~1 mwb/media/nottsco.png
git checkout $commit~1 mwb/media/nottscounty.png
git checkout $commit~1 mwb/media/nottsforest.png
git checkout $commit~1 mwb/media/oldham.png
git checkout $commit~1 mwb/media/oxford.png
git checkout $commit~1 mwb/media/peterboro.png
git checkout $commit~1 mwb/media/peterborough.png
git checkout $commit~1 mwb/media/place.jpg
git checkout $commit~1 mwb/media/plymouth.png
git checkout $commit~1 mwb/media/portsmouth.png
git checkout $commit~1 mwb/media/portvale.png
git checkout $commit~1 mwb/media/preston.png
git checkout $commit~1 mwb/media/qpr.png
git checkout $commit~1 mwb/media/queensparkrangers.png
git checkout $commit~1 mwb/media/reading.png
git checkout $commit~1 mwb/media/reg.png
git checkout $commit~1 mwb/media/register.jpg
git checkout $commit~1 mwb/media/rochdale.png
git checkout $commit~1 mwb/media/rotherham.png
git checkout $commit~1 mwb/media/scunthorpe.png
git checkout $commit~1 mwb/media/sheffield.png
git checkout $commit~1 mwb/media/sheffieldunited.png
git checkout $commit~1 mwb/media/sheffieldweds.png
git checkout $commit~1 mwb/media/sheffieldwendesday.png
git checkout $commit~1 mwb/media/sheffwed.png
git checkout $commit~1 mwb/media/shrewsbury.png
git checkout $commit~1 mwb/media/skybet.png
git checkout $commit~1 mwb/media/socstad.png
git checkout $commit~1 mwb/media/southampton.png
git checkout $commit~1 mwb/media/southend.png
git checkout $commit~1 mwb/media/stattastic2.png
git checkout $commit~1 mwb/media/stevenage.png
git checkout $commit~1 mwb/media/stoke.png
git checkout $commit~1 mwb/media/stokecity.png
git checkout $commit~1 mwb/media/sunderland.png
git checkout $commit~1 mwb/media/sunderlanda.png
git checkout $commit~1 mwb/media/swansea.png
git checkout $commit~1 mwb/media/swanseacity.png
git checkout $commit~1 mwb/media/swindon.png
git checkout $commit~1 mwb/media/torquayunited.png
git checkout $commit~1 mwb/media/totesport.png
git checkout $commit~1 mwb/media/tottenham.png
git checkout $commit~1 mwb/media/tottenhamhotspur.png
git checkout $commit~1 mwb/media/tranmere.png
git checkout $commit~1 mwb/media/watford.png
git checkout $commit~1 mwb/media/westbrom.png
git checkout $commit~1 mwb/media/westbromwichalbion.png
git checkout $commit~1 mwb/media/westham.png
git checkout $commit~1 mwb/media/westhamunited.png
git checkout $commit~1 mwb/media/wigan.png
git checkout $commit~1 mwb/media/wiganathletic.png
git checkout $commit~1 mwb/media/williamhill.png
git checkout $commit~1 mwb/media/wolves.png
git checkout $commit~1 mwb/media/wrong.png
git checkout $commit~1 mwb/media/wycombe.png
git checkout $commit~1 mwb/media/yeovil.png
git checkout $commit~1 mwb/media/york.png
